### ISSUE TITLE
Github icon cannot display

### ISSUE THREAD

**Issue by MlgmXyysd** [JoeyBling/yilia-plus-demo#23]
![QQ截图20190917092744](https://user-images.githubusercontent.com/17919858/65004010-7028f980-d92d-11e9-920c-c133d279ea75.png)
不管是yilia还是plus都显示不出来

**Comment by JoeyBling** [comment]
你好，我几个网站的图标都是正常显示的。
![](https://user-images.githubusercontent.com/25240064/65004303-81263a80-d92e-11e9-900a-333018b5a1ba.png)

**Comment by MlgmXyysd** [comment]
> 你好，我几个网站的图标都是正常显示的。
> ![](https://user-images.githubusercontent.com/25240064/65004303-81263a80-d92e-11e9-900a-333018b5a1ba.png)

什么浏览器？手机显示正常，两台电脑都显示不出来github的图标，一台电脑是chrome，另一台是360安全浏览器

**Comment by JoeyBling** [comment]
`google`、`IE`都可以的哦。你访问的网址是什么？

**Comment by MlgmXyysd** [comment]
https://joeybling.github.io/yilia-plus-demo/

**Comment by MlgmXyysd** [comment]
应该是chrome的问题，edge和ie测试正常

**Comment by JoeyBling** [comment]
你试试访问，或者你清除下缓存试试，应该不是chrome的问题
- [https://zhousiwei.gitee.io/yilia-plus-demo/](https://zhousiwei.gitee.io/yilia-plus-demo/)

**Comment by MlgmXyysd** [comment]
![QQ截图20190917094201](https://user-images.githubusercontent.com/17919858/65004572-6ef8cc00-d92f-11e9-964b-d86e3691d506.png)
缓存已禁用

**Comment by JoeyBling** [comment]
唔。很奇怪诶，你能方便看看这个图标的class属性吗，例如
![](https://user-images.githubusercontent.com/25240064/65004716-f3e3e580-d92f-11e9-925c-abbf0d50dab4.png)

**Comment by MlgmXyysd** [comment]
![image](https://user-images.githubusercontent.com/17919858/65004797-3279a000-d930-11e9-8a92-bc4d073eb884.png)

**Comment by MlgmXyysd** [comment]
::before没了

**Comment by JoeyBling** [comment]
你试试访问下这个链接，看看能不能在里面搜索到`icon-github`样式值.
- [https://zhousiwei.gitee.io/yilia-plus-demo/main.0b5690.css](https://zhousiwei.gitee.io/yilia-plus-demo/main.0b5690.css)

![](https://user-images.githubusercontent.com/25240064/65004863-7d93b300-d930-11e9-8f90-683eba580453.png)

**Comment by MlgmXyysd** [comment]
很奇怪，好像是abp的锅，但是abp并没有显示拦截数量
![image](https://user-images.githubusercontent.com/17919858/65004860-78ceff00-d930-11e9-87d0-196f46246493.png)
关掉后正常
![image](https://user-images.githubusercontent.com/17919858/65004889-91d7b000-d930-11e9-8741-cd87fd5ac138.png)
其他图标是正常的这就很迷

**Comment by JoeyBling** [comment]
我用的是`AdBlock`，貌似它并没有在我的站点上运行拦截
![](https://user-images.githubusercontent.com/25240064/65004930-c0558b00-d930-11e9-949b-c2a304d42d7a.png)

**Comment by MlgmXyysd** [comment]
我这也是显示此页面0项

**Comment by JoeyBling** [comment]
我装下这个插件调试下

**Comment by MlgmXyysd** [comment]
好的

**Comment by JoeyBling** [comment]
麻烦你看下你的ADP的过滤设置，看看是不是误操作设置了拦截
![](https://user-images.githubusercontent.com/25240064/65005099-55f11a80-d931-11e9-8c02-9271f766e575.png)

**Comment by MlgmXyysd** [comment]
![image](https://user-images.githubusercontent.com/17919858/65005161-81740500-d931-11e9-94b2-09aaf6d6cb55.png)
![image](https://user-images.githubusercontent.com/17919858/65005169-8638b900-d931-11e9-97a2-d86e4f575668.png)
![image](https://user-images.githubusercontent.com/17919858/65005180-8fc22100-d931-11e9-865f-7e49510cad62.png)
过滤列表是空的，我没设置任何网站

**Comment by JoeyBling** [comment]
貌似是设置了这个的问题

![](https://user-images.githubusercontent.com/25240064/65005292-f0e9f480-d931-11e9-9a85-f841ad1ff8e6.png)

-----

> **取消勾选**

![](https://user-images.githubusercontent.com/25240064/65005311-10811d00-d932-11e9-823b-a9d959f58649.png)

**Comment by MlgmXyysd** [comment]
ok，可以正常显示了
