### ISSUE TITLE
你好，看板娘在vuepress中请求失败了，能帮我看下什么问题吗

### ISSUE THREAD

**Issue by ghost** [JoeyBling/yilia-plus-demo#26]
![image](https://user-images.githubusercontent.com/37829038/88750763-c808d180-d188-11ea-8869-0f910a5b73ac.png)
在localhost中没问题，但是发布到github就不行了

**Comment by JoeyBling** [comment]
`vuepress` ???

**Comment by ghost** [comment]
是的，我在vuepress中安装了您的看板娘插件，在本地上可以跑，但是打包后似乎就不行了
![image](https://user-images.githubusercontent.com/37829038/88751011-4feedb80-d189-11ea-88a5-8b6138d51fd4.png)

**Comment by JoeyBling** [comment]
...地址别搞错，这是hexo的yilia-plus主题Demo
> https://github.com/JoeyBling/vuepress-plugin-helper-live2d
把博客地址发出来我看看

**Comment by ghost** [comment]
https://yejianghuai.github.io/
麻烦帮我看下，谢谢大佬

**Comment by JoeyBling** [comment]
> https://yejianghuai.github.io/
> 麻烦帮我看下，谢谢大佬

404,进不去

**Comment by ghost** [comment]
emmmm，似乎是github今天的问题，我朋友似乎也要打开梯子才能上去，上一次好像就好了，我也不知道为什么
![image](https://user-images.githubusercontent.com/37829038/88751342-f63ae100-d189-11ea-9167-ed0fed3dfb9f.png)
https://yejianghuai.github.io/

**Comment by JoeyBling** [comment]
你自己的问题，我的网站都正常可以进
> https://joeybling.github.io/

**Comment by JoeyBling** [comment]
你自己的问题，我的网站都正常可以进
> https://joeybling.github.io/

**Comment by ghost** [comment]
emmmm，好吧，谢谢了

**Comment by JoeyBling** [comment]
其他网站有没有，我看了下好像你根本没引入插件，线上的地址没看到

**Comment by ghost** [comment]
https://github.com/Yejianghuai/docs
这个是我源码的地址，您可以看下

**Comment by JoeyBling** [comment]
而且你访问的地址是这个，我不知道你那里是怎么用主域名去访问的
> https://yejianghuai.github.io/docs

**Comment by ghost** [comment]
emmm，我基本上全是默认的配置，没动。。。

**Comment by ghost** [comment]
只用了github的域名，没有买新的域名

**Comment by JoeyBling** [comment]
![](https://user-images.githubusercontent.com/25240064/88752285-1f5c7100-d18c-11ea-8847-7d7b1cfc1ede.png)
没问题啊

**Comment by ghost** [comment]
难过的一天，主要还是本地没问题，发布了就不行
![image](https://user-images.githubusercontent.com/37829038/88752416-6b0f1a80-d18c-11ea-92bc-7460008b552b.png)
![image](https://user-images.githubusercontent.com/37829038/88752431-75311900-d18c-11ea-8913-623c8493f33d.png)

**Comment by JoeyBling** [comment]
用这个网址去访问
> https://yejianghuai.github.io/docs

**Comment by JoeyBling** [comment]
我估计你是本地修改了hosts文件，反正我主域名是访问不到的

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/37829038/88752534-c2ad8600-d18c-11ea-8d48-d3dd25c82c23.png)
haoxaing好像是网络的问题。。。。。。。。。
我开了梯子以后快乐就出来了，谢谢大佬
